export const browserCoreExamples = [
  "promptx browser status",
  "promptx browser start",
  "promptx browser stop",
  "promptx browser tabs",
  "promptx browser open https://example.com",
  "promptx browser focus abcd1234",
  "promptx browser close abcd1234",
  "promptx browser screenshot",
  "promptx browser screenshot --full-page",
  "promptx browser screenshot --ref 12",
  "promptx browser snapshot",
  "promptx browser snapshot --format aria --limit 200",
  "promptx browser snapshot --efficient",
  "promptx browser snapshot --labels",
];

export const browserActionExamples = [
  "promptx browser navigate https://example.com",
  "promptx browser resize 1280 720",
  "promptx browser click 12 --double",
  'promptx browser type 23 "hello" --submit',
  "promptx browser press Enter",
  "promptx browser hover 44",
  "promptx browser drag 10 11",
  "promptx browser select 9 OptionA OptionB",
  "promptx browser upload /tmp/file.pdf",
  'promptx browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "promptx browser dialog --accept",
  'promptx browser wait --text "Done"',
  "promptx browser evaluate --fn '(el) => el.textContent' --ref 7",
  "promptx browser console --level error",
  "promptx browser pdf",
];
